#!/usr/bin/env python

# ----------------------------------------------------------------------
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and/or hardware specification (the "Work") to
# deal in the Work without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Work, and to permit persons to whom the Work
# is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Work.
#
# THE WORK IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE WORK OR THE USE OR OTHER DEALINGS
# IN THE WORK.
# ----------------------------------------------------------------------

# Get floating point division from Python 3
from __future__ import division

import sys

import geni.aggregate.instageni as IG
import geni.util

# Ignore these sites when searching. These are development sites
# or should be ignored for some other reason.
IGNORED_SITE_NAMES = ['ig-utah', 'ig-gpo', 'ig-princeton', 'ig-utahddc']


def get_ad(context, site):
    ad = None
    try:
        ad = site.listresources(context)
    except Exception:
        # Log a notice of some kind?
        # What sorts of exceptions are raised by listresources?
        pass
    return ad


def get_xen_load(ad):
    site_nodes = 0
    site_avail = 0
    for node in ad.nodes:
        if not node.exclusive and 'emulab-xen' in node.sliver_types:
            site_nodes += 1
            avail = int(node.hardware_types["pcvm"])
            site_avail += avail
    # Note this uses __future__ division to get a float from two ints
    score = site_avail / site_nodes
    return score


def available_raw_pcs(ad):
    avail = [node for node in ad.nodes
             if (node.available and node.exclusive and
                 'raw-pc' in node.sliver_types)]
    return len(avail)


def site_cmp(site1, site2):
    if site1.xen_score == site2.xen_score:
        return cmp(site1.raw_score, site2.raw_score)
    else:
        return cmp(site1.xen_score, site2.xen_score)


def candidate_sites():
    return IG.aggregates()
    return [IG.Cornell, IG.UMichigan, IG.Utah, IG.UtahDDC, IG.SOX]


def get_possible_sites(context):
    """Find the possible sites where our topology could be instantiated.
    """
    possible_sites = []
    for site in candidate_sites():
        if site.name in IGNORED_SITE_NAMES:
            continue
        ad = get_ad(context, site)
        if not ad:
            # Site is probably down
            continue
        raw_score = available_raw_pcs(ad)
        if raw_score < 1:
            print 'Skipping %s, no bare metal available.' % (site.name)
            continue
        site.raw_score = raw_score
        xen_score = get_xen_load(ad)
        if xen_score > 0:
            site.xen_score = xen_score
            site.ad = ad
            possible_sites.append(site)
    print '\n\n-=-=-=-=-=-=-=-=-=-=-\n\n'
    # Sort the best candidates to the front of the list
    possible_sites.sort(cmp=site_cmp, reverse=True)
    for site in possible_sites:
        pretty_xen_score = int(round(site.xen_score))
        print 'Site %s: %d raw, xen score %d)' % (site.name, site.raw_score,
                                                  pretty_xen_score)
    return possible_sites


def main(argv=None):
    if not argv:
        argv = sys.argv
    context = geni.util.loadContext(key_passphrase=True)
    # Now make the request rspec
    possible_sites = get_possible_sites(context)
    site = possible_sites[0]
    print 'Building rspec for %s' % (site.name)
    # Get available raw_pc nodes, choose first
    # Create request for that, including the interface component_ids
    # See 2-vm-2-host.py sample
    # See rawpc3intf.py sample


if __name__ == '__main__':
    main(sys.argv)
